server:
  port: 8080

demo-config:
  param1: some param 1
  not-required-param: not required param
  sub-config:
    sub-config-param1: sub some param 2
    sub-config-not-required-param: sub not required param
